config/routes.rb
Rails.application.routes.draw do
  resources :employees
  get "employee_taxes", to: "employees#taxes"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :first_name, presence: true, length: { maximum: 100 }
    validates :last_name,  presence: true, length: { maximum: 100 }
    validates :email, presence: true, uniqueness: true
    validates :phone_number, :employee_id, presence: true
    validates :date_of_join, :salary, presence: true

    def annual_salary(employee)
    	employee.salary*12
    end

    def tax_amount(employee)
        yearly_salary = annual_salary(employee) 
        unless employee.date_of_join <= Date.parse("01 Apr 2023")
        	yearly_salary = (365-(employee.date_of_join-Date.parse("01 Apr 2023")))*(yearly_salary/365)
        end
    	
    	if yearly_salary <= 250000
    		"no tax"
    	elsif yearly_salary > 250000 && yearly_salary <= 500000
    		yearly_salary*0.05 
    	elsif yearly_salary > 500000 && yearly_salary <= 1000000
    		yearly_salary*0.1
    	else
            yearly_salary*0.2
    	end
	   

    end

    def cess_amount(employee)
    	yearly_salary = annual_salary(employee)
    	if yearly_salary >= 2500000
    		yearly_salary*0.02
    	end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: 'Employee was successfully created.' 
    else
      render :new 
    end 
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Employee was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_url, notice: 'Employee was successfully destroyed.' 
  end

  def taxes
    @employees = Employee.all
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:employee_id, :first_name, :last_name, :email, :phone_number, :date_of_join, :salary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_Id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_area :phone_number %>
  </div>
  <div class="field">
    <%= f.label :date_of_join %><br>
    <%= f.date_select :date_of_join %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Date of join</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_id %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone_number %></td>
        <td><%= employee.date_of_join %></td>
        <td><%= employee.salary %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee Id:</strong>
  <%= @employee.employee_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @employee.phone_number %>
</p>

<p>
  <strong>Date of join:</strong>
  <%= @employee.date_of_join %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/taxes.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees Taxes</h1>

<table>
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Yearly salary</th>
      <th>Tax Amount</th>
      <th>Cess Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_id %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.annual_salary(employee) %></td>
        <td><%= employee.tax_amount(employee) %></td>
        <td><%= employee.cess_amount(employee) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>